apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-connect
  template:
    metadata:
      labels:
        app: city-connect
    spec:
      containers:
        - name: city-connect
          image: registry.bastian-somon.fr/city-connect:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-creds