apiVersion: v1
kind: Service
metadata:
  name: city-connect # Sets service name
  labels:
    app: city-connect # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 8080
      name: http
  selector:
    app: city-connect
