apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: city-connect

patches:
  # - target:
  #     kind: Deployment
  #     name: javadoc
  #   path: ./patches/javadoc-deployment.yml
  - target:
      kind: Deployment
      name: server
    path: ./patches/backend-deployment.yml
