apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: city-connect

patches:
  - target:
      kind: Ingress
      name: city-connect-ingress
    path: ./patches/ingress.yml
  - target:
      kind: Deployment
      name: backend
    path: ./patches/backend-deployment.yml
  - target:
      kind: Deployment
      name: frontend
    path: ./patches/frontend-deployment.yml
