apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: city-connect-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

spec:
  ingressClassName: nginx
  rules:
    - host: city-connect.bastian-somon.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: city-connect
                port:
                  number: 8080
  tls:
    - hosts:
        - '*.bastian-somon.fr'
      secretName: letsencrypt-tls-cert
