apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sandbox-city-connect

patches:
  - target:
      kind: Ingress
      name: city-connect-ingress
    path: ./patches/ingress.yml
